title: Decentralized Namespace
description: GitHub Documentation

url: "https://ns.did.ai"

defaults:
  - scope:
      path: "did/**/*.*"
    values:
      sitemap: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap

theme: jekyll-theme-architect